version: '3'

services:
  supertokens-db:
    hostname: supertokens-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${SUPERTOKENS_DB_PASS}
      MYSQL_USER: ${SUPERTOKENS_DB_USER}
      MYSQL_PASSWORD: ${SUPERTOKENS_DB_PASS}
      MYSQL_DATABASE: supertokens

    networks:
      - game_node_app
    restart: always
    volumes:
      - supertokens-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  supertokens:
    hostname: supertokens
    image: registry.supertokens.io/supertokens/supertokens-mysql:7.0

    depends_on:
      - supertokens-db

    environment:
      MYSQL_CONNECTION_URI: mysql://${SUPERTOKENS_DB_USER}:${SUPERTOKENS_DB_PASS}@supertokens-db:3306/supertokens

    networks:
      - game_node_app
    restart: always

    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5


  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: gamenode

    networks:
      - game_node_app
    restart: always
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  redis:
    image: redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'

    restart: always

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

    volumes:
      - redis:/var/lib/redis

    networks:
      - game_node_app

  server:
    image: lamarcke/game-node-server:latest

    # Most of the env vars are loaded directly from .env, we only need to override some to make sure
    # the docker resources are accessible.
    environment:
      DB_HOST: db
      DB_DATABASE: gamenode
      DB_PASS: ${DB_PASS}
      DB_USER: ${DB_USER}
      DB_PORT: 3306
      SUPERTOKENS_CORE_URI: http://@supertokens:3567
      REDIS_URL: redis://redis:6379
      SERVER_PORT: 5000
      DOMAIN_API: https://server.gamenode.app
      DOMAIN_WEBSITE: https://gamenode.app

    healthcheck:
      test: [ "CMD-SHELL", "yarn run healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 3

    restart: always

    volumes:
      - gamenode:/app/public/uploads
      - gamenode:/app/public/icons

    command: ["yarn", "start"]

    networks:
      - game_node_app

networks:
  game_node_app:
    external: true

volumes:
  redis:
  db:
  gamenode:

