export const AUTH_ERRORS = {
    MISSING_PROVIDER_EMAIL_ERROR: "AUTH_MISS_PROV_MAIL_ERR",
    USER_INIT_ERROR: "AUTH_USER_INIT_ERR",
    UNVERIFIED_EMAIL_CONFLICT: "UNVERIFIED_EMAIL_CONFLICT",
    UNVERIFIED_EMAIL_REQUIRED: "UNVERIFIED_EMAIL_REQUIRED",
    PROVIDER_LINK_CONFLICT: "PROVIDER_LINK_CONFLICT",
    PROVIDER_EMAIL_CHANGED: "PROVIDER_EMAIL_CHANGED",
    DUPLICATE_LEGACY_ACCOUNTS: "DUPLICATE_LEGACY_ACCOUNTS",
} as const;

/**
 * Supertokens' default tenant id
 */
export const DEFAULT_TENANT_ID = "public";
